on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build Storybook
        run: npx build-storybook

      - name: Lost Pixel
        uses: lost-pixel/lost-pixel@v3.5.2
